<div class="jumbotron bg-primary">
	<h1 class="display-3"><?=$config['title']['full']?></h1>
	<p class="lead">
		Ease your life when trying to get a license for your business!
	</p>
	<hr class="my-2">
	<?=$session->message()?>
	<p class="lead">
		<a id="nav-btn" class="btn btn-success" href="login.php">
			Login
		</a>
		<a id="nav-btn" class="btn btn-info" href="register.php">
			Register
		</a>
	</p>
</div>